version: '3'

services:
  challenge_application:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - "db"
    ports:
      - "8090:8090"
    links:
      - "db"
  db:
    image: postgres:13-alpine
    environment:
      POSTGRES_PASSWORD: "challenge"
      POSTGRES_USER: "challenge"
      POSTGRES_DB: "challenge"
    ports:
      - "5433:5432"