// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// AppRouter is an autogenerated mock type for the AppRouter type
type AppRouter struct {
	mock.Mock
}

// InitializeHttpServer provides a mock function with given fields:
func (_m *AppRouter) InitializeHttpServer() {
	_m.Called()
}
