// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	dto "github.com/znobrega/file-storage/pkg/dto"

	usecases "github.com/znobrega/file-storage/pkg/domain/usecases"
)

// DeleteFiles is an autogenerated mock type for the DeleteFiles type
type DeleteFiles struct {
	mock.Mock
}

// Execute provides a mock function with given fields: ctx, deleteFiles
func (_m *DeleteFiles) Execute(ctx context.Context, deleteFiles usecases.DeleteFilesParam) ([]dto.FilePublic, error) {
	ret := _m.Called(ctx, deleteFiles)

	var r0 []dto.FilePublic
	if rf, ok := ret.Get(0).(func(context.Context, usecases.DeleteFilesParam) []dto.FilePublic); ok {
		r0 = rf(ctx, deleteFiles)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]dto.FilePublic)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, usecases.DeleteFilesParam) error); ok {
		r1 = rf(ctx, deleteFiles)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
