// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	dto "github.com/znobrega/file-storage/pkg/dto"

	usecases "github.com/znobrega/file-storage/pkg/domain/usecases"
)

// FindFilesById is an autogenerated mock type for the FindFilesById type
type FindFilesById struct {
	mock.Mock
}

// Execute provides a mock function with given fields: ctx, data
func (_m *FindFilesById) Execute(ctx context.Context, data usecases.FindFileByIdParam) (*dto.FilePublic, error) {
	ret := _m.Called(ctx, data)

	var r0 *dto.FilePublic
	if rf, ok := ret.Get(0).(func(context.Context, usecases.FindFileByIdParam) *dto.FilePublic); ok {
		r0 = rf(ctx, data)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.FilePublic)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, usecases.FindFileByIdParam) error); ok {
		r1 = rf(ctx, data)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
