// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	dto "github.com/znobrega/file-storage/pkg/dto"

	usecases "github.com/znobrega/file-storage/pkg/domain/usecases"
)

// ListFilesById is an autogenerated mock type for the ListFilesById type
type ListFilesById struct {
	mock.Mock
}

// Execute provides a mock function with given fields: ctx, ListFilesById
func (_m *ListFilesById) Execute(ctx context.Context, ListFilesById usecases.ListFilesByIdParam) ([]dto.FilePublic, error) {
	ret := _m.Called(ctx, ListFilesById)

	var r0 []dto.FilePublic
	if rf, ok := ret.Get(0).(func(context.Context, usecases.ListFilesByIdParam) []dto.FilePublic); ok {
		r0 = rf(ctx, ListFilesById)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]dto.FilePublic)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, usecases.ListFilesByIdParam) error); ok {
		r1 = rf(ctx, ListFilesById)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
