// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	dto "github.com/znobrega/file-storage/pkg/dto"

	usecases "github.com/znobrega/file-storage/pkg/domain/usecases"
)

// ListFiles is an autogenerated mock type for the ListFiles type
type ListFiles struct {
	mock.Mock
}

// Execute provides a mock function with given fields: ctx, listFiles
func (_m *ListFiles) Execute(ctx context.Context, listFiles usecases.ListFilesParam) (*dto.FileResponse, error) {
	ret := _m.Called(ctx, listFiles)

	var r0 *dto.FileResponse
	if rf, ok := ret.Get(0).(func(context.Context, usecases.ListFilesParam) *dto.FileResponse); ok {
		r0 = rf(ctx, listFiles)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.FileResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, usecases.ListFilesParam) error); ok {
		r1 = rf(ctx, listFiles)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
