// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	dto "github.com/znobrega/file-storage/pkg/dto"
)

// ListDirectories is an autogenerated mock type for the ListDirectories type
type ListDirectories struct {
	mock.Mock
}

// Execute provides a mock function with given fields: ctx
func (_m *ListDirectories) Execute(ctx context.Context) (*dto.Directories, error) {
	ret := _m.Called(ctx)

	var r0 *dto.Directories
	if rf, ok := ret.Get(0).(func(context.Context) *dto.Directories); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.Directories)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
