// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	entities "github.com/znobrega/file-storage/pkg/domain/entities"

	usecases "github.com/znobrega/file-storage/pkg/domain/usecases"
)

// SaveFilesOnFileSystem is an autogenerated mock type for the SaveFilesOnFileSystem type
type SaveFilesOnFileSystem struct {
	mock.Mock
}

// Execute provides a mock function with given fields: fileData
func (_m *SaveFilesOnFileSystem) Execute(fileData usecases.SaveFilesParam) ([]entities.File, error) {
	ret := _m.Called(fileData)

	var r0 []entities.File
	if rf, ok := ret.Get(0).(func(usecases.SaveFilesParam) []entities.File); ok {
		r0 = rf(fileData)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entities.File)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(usecases.SaveFilesParam) error); ok {
		r1 = rf(fileData)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
