// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	dto "github.com/znobrega/file-storage/pkg/dto"

	usecases "github.com/znobrega/file-storage/pkg/domain/usecases"
)

// UpdateFileBlob is an autogenerated mock type for the UpdateFileBlob type
type UpdateFileBlob struct {
	mock.Mock
}

// Execute provides a mock function with given fields: ctx, UpdateFileBlob
func (_m *UpdateFileBlob) Execute(ctx context.Context, UpdateFileBlob usecases.UpdateFileBlobParam) (*dto.FileResponse, error) {
	ret := _m.Called(ctx, UpdateFileBlob)

	var r0 *dto.FileResponse
	if rf, ok := ret.Get(0).(func(context.Context, usecases.UpdateFileBlobParam) *dto.FileResponse); ok {
		r0 = rf(ctx, UpdateFileBlob)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.FileResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, usecases.UpdateFileBlobParam) error); ok {
		r1 = rf(ctx, UpdateFileBlob)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
